apiVersion: v1
kind: ConfigMap
metadata:
  name: springboot-kubernetes-configmap
data:
  application.properties: |-
    webservice.endpoint.transferfund=test
    webservice.endpoint.getbalance=test
    webservice.endpoint.customerinfo=test
