apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-git-test-watcher
  namespace: default
data:
  hello: hello_value
  name: personname
  app: googlepay
  test: success
  test_two: success
  test_cronjob: success
  test_cronjob_test: success
